### ISSUE TITLE
Answers not matching questions 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1788] opened 2021-03-24 14:45 UTC
I am really not sure how to name this issue, but will try to explain the problem as detailed as I can. The issue came from Carmen, who working on a dataset noticed the for 2 gender option questions, where the defined options in the form are `Female` and `Male` the dataset holds also values `1`, `0`, `2`. These values come from form version 6. But there are submissions from form version 6 that have the correct expected. values. There is no linkage to the wrong values and an enumerator either. 

The question was Why is this data different? 

* akvoflow-194
* /NKG Bloom/NKG Bloom - Kenya survey/NKG Bloom - Kenya survey
* FormId: 148080024
* Form version: 6 and higher 
* 2 questions in Group 24, question ID: 125680548 and 134880519

# What I found and assumptions that I checked: 

## Could this be a case of options and option codes mixing up? 
**Answer:** No 

**Why:**
* Form version 5 - does not even have these questions 
* Form version 6 - holds the questions, they are well defined as option questions with the 2 expected options  and the options do not have codes defined

## Could it be that the values were overwritten via Data cleaning? 
**Answer:** No 

**Why:**
@tangrammer checked the events related to the form and found that data cleaning happened on `2021-01-29 (16:43:58.656) CET`. He got the data files exported and imported to this survey form. There is a data export made on `2021-01-20 at 15:26`. This one holds submissions to version 5 and version 6 but no data for the gender questions. The next export file is from `2021-01-29 at 11:34` and this sheet has the wrong values for the gender question. 

So I asked @muloem if he could get me the json file sent from the Flow app for the submission with instance ID: `127350111` as this one has the wrong values in both columns in the excel file from the `2021-01-29 at 11:34`. Looking at the values in the json file sent from the app, the submissions are made to `form version 6` and answers to both questions show exactly the data in the sheet - **wrong values**. 

![Screenshot 2021-03-24 at 14 05 06](https://user-images.githubusercontent.com/12456965/112329150-3d488a00-8cb7-11eb-9316-ff9e84062c8a.png)

![Screenshot 2021-03-24 at 14 05 52](https://user-images.githubusercontent.com/12456965/112329198-489bb580-8cb7-11eb-97f2-fb9440accad5.png)

This means that the Flow app sent wrong data to an option question, numbers, despite the fact that the from version should only allow the user to select either Male or Female. 

## Is it possible something went wrong in the app? 

**Answer:** ? 

The idea is that maybe the enumerator had a draft submission made to version 5, received version 6 and continued with the draft version. This means that the submission is made the version 6 of the form, but maybe the questions did not show well. 
* Why we think this could be the problem? Because version 5 of the form did not even have those questions and version 6 does 
* The wrong data is linked to version 6
* When looking at the pattern of 1 enumerator who submitted wrong data to version 6, then on the same day 2 hours later right data to version 6 - we could guess that she might have started with version 5 and then received version 6 in that day

In an update on this issue, I will try to prove this assumption on uat1.

**Comment by janagombitova** [comment] 2021-03-25 10:55
I could not reproduce the error. The steps I took: 
1. Created a survey on uat1 > _ _Jana > Issue 1788 > Issue 1788
2. Published it to `form version 3`
3. Assigned the form to my device
4. Submitted two data points and left one in `darft/saved` mode 
4. Made changes to the survey from and published `version 4`
5. Closed and opened the app to trigger the download on the new version 
6. Opened a new submission to check the form version, it was version 4
7. Reopened my draft submission, saw that the questions changed matching version 4, but in the header it stil lsaid version 3. 
8. Finished the submission also adding data to the new questions 
9. Submitted 
10. Downloaded the Data cleaning export and saw: 
   * Data was correct - **I could not reproduce the error** 
   * The submissions stated version 3 even thought it was actually version 4   

![Screenshot_2021-03-24-19-51-51](https://user-images.githubusercontent.com/12456965/112461237-08444200-8d60-11eb-892d-88706a7589a1.png)

![Screenshot 2021-03-24 at 19 54 57](https://user-images.githubusercontent.com/12456965/112367935-d63ccc80-8cda-11eb-8d27-74aeedead71f.png)

## Is it possible something went wrong in the app?
**Answer** : Not related to the data issue 

**Issues found:** 
* there was no visual indication that the new form version was downloaded to my app. We have the new or updated surveys now bold in the Survey menu, but if you have the survey already selected there is no way for you to know that the verison of the form was updated (only if you remember the number of the old version and now the new one)
* the form version of my draft submission stated to be in version 3 but the actual questions showed version 4. The submission also states still version 3 even thought it was actually version 4. 

## Could this issue be caused by our unclear publishing UX?

Is it possible that the survey was published in version 6 but the user continued to make futher changes, before the publishing completed (did not go to the messages tab) and then published version 6 again? Is it possible to have 2 versions of a form of the same number? 

We know the publishing of forms in Flow still has one risk:https://github.com/akvo/akvo-flow/issues/3619 Maybe that could be the reason for this issue. 

## ? Could there be another reason behind this data issue?

**Comment by valllllll2000** [comment] 2021-04-05 15:33
![Screenshot from 2021-04-05 17-20-17](https://user-images.githubusercontent.com/923280/113590814-68c26180-9633-11eb-87d9-756be585b98c.png)

I have managed to reproduce this issue, steps
1) Add 2 text questions to a form
2) Publish but don't close the form page nor reload the page
3) Make sure to download the form to the device 
4) Fill the answer but do not press submit (leave the phone in the submit tab)
5) Update the answers by making them options
6) Publish
7) Submit on the device
8) In the app settings user "reload all surveys". Because the version is still the same, if you don't do this the new updated questions will not be downloaded unless you do it this way.
9) Open a new datapoint and submit again. This time you will see that the form has 2 option questions and not text
10) Export the data, you will see that for the same version there are answers for 2 different question types

What fixes can be done on the app:
see suggestions in #1544 which are all related to updating the form version

The rest should be fixed in the backend, we need to find a way to make the user reload the page after publishing or disable the publish button until publishing is completed.

**Comment by valllllll2000** [comment] 2021-04-14 17:53
closing as there is nothing that can be done more on the app, some changes were released to fix the version inconsistencies

**Closed by valllllll2000** 2021-04-14 17:53 UTC
Labels: Bug
