### ISSUE TITLE
Secure collected data and images

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#977] opened 2018-01-04 13:18 UTC
As described here https://github.com/akvo/akvo-product-design/issues/287 for the new GDPR law we need to secure/restrict access to collected data.

**Current situation**
Collected data and media are located in public folder and user and other apps can easily access them. The reason it is like this the ability to manually upload to flow the exported files. The user connect the device to the PC, browsers the device's filesystem and copies those files to the PC. She then uploads them via the dashboard.

**GDPR Compliant solution**
The collected files and media (images, videos...) will be kept in the app internal private storage by defaults. Only our app can access those files. If the user wants to export the files manually, shell will have to enable the export of these files to the public folder. 

**Sharing options**
1) Enable the the exporting of files once for all the surveys? In that case, we can have an entry inside settings which will enable this once and all the existing and future files will be public. 
2) Add a "share" entry to navigation drawer and then each time user presses it we will share/export all the existing collected data.
3) Add a "share" entry to navigation drawer which would display a list of all the existing files and user can select with a checkbox which ones she want to export.

**Comment by janagombitova** [comment] 2018-01-23 10:29
Today we spoke with @valllllll2000 and @Kiarii on this issue, how it will affect users workflow, what the value is and suggested changes that we want to test out. Here if the full mural board we used: https://app.mural.ly/t/akvo8194/m/akvo8194/1516696336378/c6e547785ade91da38f0fd4a9cef8df8f8824f1d and here is an image of the new changes and how users' workflow will look like. 

![screen shot 2018-01-23 at 11 28 41](https://user-images.githubusercontent.com/12456965/35270841-98606e2e-0030-11e8-915d-d247ff809473.png)

Secondly we spoke about how to let users know about that change after they update the app and agreed to use a walkthrough https://github.com/Shashank02051997/FancyWalkthrough-Android. See this issue https://github.com/akvo/akvo-flow-mobile/issues/984

**Comment by Kiarii** [comment] 2018-01-26 09:02
we decided to start here and do some user tests to validate the idea..

![image](https://user-images.githubusercontent.com/12692444/35432283-3c9b3f9c-0288-11e8-8aa0-68fc681bdd10.png)

**Comment by janagombitova** [comment] 2018-04-11 12:00
Tested everything over the last two days and all seems to work fine. I have experienced it once when the app crashed: https://github.com/akvo/akvo-flow-mobile/issues/1075. I will continue testing this week but so far nothing alarming has revealed itself. 👍 Well done.

There is one thing I noticed, and not sure if this is ok or not: 
1. captured data offline
2. hit publish 
3. bulk uploaded the published file 
4. uninstalled the app 
5. installed the app 
6. in Settings the Publish data option is enabled but I still have the published folder in the public file with the data

There is a low chance anyone will do this in practice, but should the published folder be also deleted if someone uninstalls the app before the 90 minutes pass?

**Comment by valllllll2000** [comment] 2018-04-11 12:53
@janagombitova I will check it out but I think there is no way to delete the data if the app in uninstalled. The private folders do get deleted but the public does not.

**Comment by janagombitova** [comment] 2018-04-11 12:59
@valllllll2000 ok. Thank you. If not possible, once you check, I will make sure to add it to the documentation so we have it noted on support.

**Comment by valllllll2000** [comment] 2018-04-11 13:04
@janagombitova OK so it is not possible but we could pleace the files in a diferent place and in that case, they would be automatically deleted. The drawback, they would be harder to find: /Android/data/org.akvo.flow/files/exported if I place them there, when user uninstalls the app, all that files will be deleted

**Comment by valllllll2000** [comment] 2018-04-11 13:32
@janagombitova the akvoflow/inbox can stay as it is but if we want them to also be deleted with app uninstall, then they should also be moved. The folders can be named any way you want but they start with `/Android/data/org.akvo.flow/files/` and then you can name it akvoflow or akvoflow/data or akvoflow/exported etc...

**Comment by janagombitova** [comment] 2018-04-11 14:00
@valllllll2000 This question is actually quite important I realise just now, because it brings about the situation: user uses Flow app and then stops working on the project and uninstalls the app, but in this situation (publishing and uninstalling in the 90 min limit) he will still have the data on his device and thus accessible. According the to data protection laws out there by uninstalling the app he loses legal grounds to have the data, thus he should not have it. So our current way is not the most responsible way to handle things (I also checked with Lynn). 

I also realise that the chances for this to happen are low, but still there is a chance. So once you uninstall Flow, everything should be gone (all folders too). So in the notion of privacy by design and the reasoning above, we should move the flow folder under /Android (we actually already have it there with cache and files).

I was also considering to limit the publishing time, but that does not resolve the fact that the folders (even if empty) stay behind after uninstalling the app. 

The only thing that holds me back from saying 'yes, do it' is that it will be harder for the user to find the folder the 1st time he has to bulk upload. Would it be possible to not allow to uninstall the app before the 90 minutes of publishing have passed? Then we can keep the folders as they are and after the 90 minutes no data is available in the public folder anymore.

**Comment by valllllll2000** [comment] 2018-04-11 14:08
@janagombitova I do not have control over installs and uninstalls of the app. I cannot prevent users from uninstalling the app, it is not possible.

**Comment by janagombitova** [comment] 2018-04-11 14:11
@valllllll2000 ah, that is too bad. 

Then we need to move the folder and adjust the walkthrough in the UI on the bulk uplaod page to make finding the folder easier. Sorry that this change came up so late in the implementation. I did not realise it only till now.

**Comment by valllllll2000** [comment] 2018-05-14 09:15
## Test plan
This is the generic issue with the feature specs, test plans are indicated in each detailed issue.

**Comment by janagombitova** [comment] 2018-05-14 10:35
Moving it to ready for release as most of the issues are completed and tested. The remaining issues are logged. 👍 I am really happy to see this coming to life. Well done. It is an important milestone.

**Closed** 2018-06-06 19:07 UTC
Labels: DataPrivacy, New and noteworthy, Ready for release
