### ISSUE TITLE
Map not updating point location after data cleaning 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#869] opened 2017-09-11 09:10 UTC
# Context
I have tested this issue, https://github.com/akvo/akvo-flow/issues/1839,  after the hotfix release as it was linked to https://github.com/akvo/akvo-flow/issues/2229 to check if there was still a problem with answers not updating in point History after data cleaning. The problem is resolved but I noticed another issue and was not sure if it is solved in 2.4.0 or we need a new issue @valllllll2000, so I created an issue just to be sure. 

# Problem or idea 
Here are the steps I have taken: 
- created a survey form with a few questions and location question 
- synced the data to my phone
- cleaned a number question and a geolocation (use as point location) question and synced in the points (did not remove the points from the phone)
- in the History the answers updated correctly, but on the Map the points were still showing in the old location (for all points and for the individual location of the points)
- deleted all submissions from my device and synced in data points again
- points still show in the wrong location

The expectation is that if the location info is changed (is possible as the GPS might have not been calibrated well or data has been created via data cleaning import) it needs to change on the Map in the app as well. Alphonso often users the location to find the data point in the field using the Map and then submits new data for that point. The map is used often to navigate in the field and he relies on identifying the point based on its location

**Comment by valllllll2000** [comment] 2017-10-10 07:58
I have tested this issue with the 2.4.0.1 app and it still happens. Here is an example of datapoint which after being cleaned, is still displayed by the app in the wrong position:
`{"identifier":null,"lat":39.4295817,"lastUpdateDateTime":1507566424256,"lon":-3.6353993,"surveyInstances":[{"collectionDate":1507565707949,"submitter":"valeria_sony_tablet","uuid":"7389d390-d6cb-4ac2-b0ad-a7f382ba1df4","surveyId":118889115,"qasList":[{"q":"115309116","a":"cleanup candidate","t":"VALUE"},{"q":"117139116","a":"38.5237665|-8.8992069|1|514xk6gx","t":"GEO"}]}],"surveyGroupId":118879117,"displayName":"cleanup candidate","id":"10vn-ker0-qfw","keyId":null}`

As you can see here {"q":"117139116","a":"38.5237665|-8.8992069|1|514xk6gx","t":"GEO"} the question's location has been updated to latitude|longitude 38.5237665|-8.8992069 but the datapoint is still displayed using the fields "lat":39.4295817, and "lon":-3.6353993. The issue is that the backend sends these values as datapoint location, and we do not look inside each question to display the location. I think it is something that should be fixed in the backend: after cleaning data it updates the answers to the question itself but does not verify if the question is used for datapoint location and also updates the data there.

**Comment by janagombitova** [comment] 2017-10-10 14:26
@valllllll2000 @muloem and @stellanl Lumen is experiencing the same issue: A user cleaned location answers (used as data point location) in Flow and expected to see the points updated in Lumen.  @jonase also confirmed the problem. 

Considering Lumen is picking up pace we do not want Flow bugs to bring a bad user experience there and secondly this is also a consistency issue in Flow that we should resolve. 

Who is willing to pick this one up - create the issue in the proper repo and fix it for the next release (November X..X.. release)?

**Comment by jonase** [comment] 2017-10-10 14:39
If (as part of data cleaning) I add new rows and upload, the `SurveyedLocale` kind in the datastore is not updated properly and leaves a bunch of values empty (`null`). In Lumen we currently rely on `latitude` and `longitude` from the `SurveyedLocale`. 

I think the lat/long in `SurveyedLocale` is also not updated if I (instead of adding new rows) clean location data (one of lat,long,elev,geocode)

With some new Lumen features we might not need to rely on `SurveyedLocale` for location data in the future but it seems like this issue is problematic elsewhere as well

**Comment by stellanl** [comment] 2017-10-10 16:30
This is a close parallel to the datapoint name issues. Solution is probably similar; do not read from the SurveyedLocale object, but directly from the QustionAnswerStore entity that created the location.

**Comment by janagombitova** [comment] 2017-10-16 13:42
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-71638-from-nikki-at-akvo-dot-org

**Comment by janagombitova** [comment] 2017-10-30 09:50
@muloem as @stellanl is fully into exports for the upcoming releases will you be able to take over this issue?

**Comment by muloem** [comment] 2017-11-06 05:28
This will be handled under https://github.com/akvo/akvo-flow/issues/1839.

**Closed by muloem** 2017-11-06 05:28 UTC
Labels: In progress
