### ISSUE TITLE
Improve notifications readability

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#125] opened 2014-07-22 16:31 UTC
Many of the notifications displayed in the app are not fully readable in small devices. We need to make sure all the notification content fits somehow in the screen.

![device-2014-07-22-173017](https://cloud.githubusercontent.com/assets/1754343/3661098/8df6c7a4-11bd-11e4-8c82-7e0ec2f1fd67.png)

**Comment by janagombitova** [comment] 2016-11-21 13:35
Duplicate of a newer issue: https://github.com/akvo/akvo-flow-mobile/issues/519 Closing this one

**Closed by janagombitova** 2016-11-21 13:35 UTC
Labels: Defect
