### ISSUE TITLE
Use offline maps when capturing geoshapes 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1447] opened 2019-08-01 09:19 UTC
With 2.8.0 we completed the initial work on offline maps. You can create and save an offline map and view data points, or a single data point on it. However, when collecting geoshapes, we will use the old Google maps and offline maps are not supported here. 

With this issue we will: 
* NOT change how geoshapes work today (that is a larger task for another time) 
* ensure that when collecting a geoshape offline you can see the offline map and not work with a grey screen as today 

# Status quo

![geoshape](https://user-images.githubusercontent.com/12456965/62281390-fc4e9280-b44d-11e9-9244-312104c06bcc.gif)

Today when creating a geoshape you start with two action buttons in the top panel: 
* map tile selector 
* geoshape type selector - you need to select the geoshape type, to be able to proceed. 

If you are offline, the map screen will remain blank. 

# Change
How can we make it possible to use an offline map when creating new geoshapes? 
How can we make it possible to use an offline map when viewing a created geoshapes? 

@Kiarii and @valllllll2000  can you take a look at how geoshapes work today, change nothing about them but figure out how to make use of offline maps, as we do with data points?

**Comment by valllllll2000** [comment] 2019-08-01 14:20
I know this seems like an easy task but technically I still have to rewrite everything that is done using google maps into mapbox code so it's almost rewriting all from 0. If the design stays exactly the same then probably @Kiarii  does not need to get involved?? This different from datapoints as the logic for datapoints stayed the same. Here all the logic is related to drawing on the maps using a different library it will need to be rewritten.

**Comment by janagombitova** [comment] 2019-08-01 14:44
I see. My concern is that we do not know enough to adjust the implementation and on the other hand we know enough to know that once we start there are many rabbit holes to dive into (enforcing to decide on the shape type on the survey level so not allowing to decide in the field if it will be a line, points or a shape; validating the shapes, not allowing to create more than one shape per answer, etc). So improving the geoshapes is a large task on its own but does not have the priority right now. 

I would rather we finish up the offline maps, get fully rid of all google maps in the app and then later on when we prioritise needs around agricultural projects we pick up the project to clean up and improve geoshapes.

**Comment by Kiarii** [comment] 2019-08-02 07:04
@janagombitova are we then parking the issue for now?

**Comment by janagombitova** [comment] 2019-08-02 09:01
@Kiarii not this issue but re-working geoshapes from the user perspective. So Valeria will just reimplement the logic with offline maps, but we will not change anything around geoshapes until another time.

**Comment by Kiarii** [comment] 2019-08-05 09:43
so for now we only need consider the following right?
- capturing geoshapes on an offline map (incl here the ability to download/select offline map in the shape capture screen)
- viewing geoshapes on an offline map

**Comment by janagombitova** [comment] 2019-09-13 13:50
This is something I noticed when testing geoshape creation offline, with offline maps. It **did NOT** happen when working with geoshapes online. 

When creating the shape offline on an offline map, you do not see the points being added to the map. It happens and the area gets created but you do not see those orange points. 

![Screenshot_2019-09-13-14-35-59](https://user-images.githubusercontent.com/12456965/64867422-a9b3e900-d63d-11e9-9d4b-a9c0ac863caf.png)

So when you click to add your first point you do not see it happening. Or when you long click on the map to add a point, it does not show and then you add a second one - it does not show and only once you add the third one you see the area. So you have no clue the shape is happening. 

![geoshape3](https://user-images.githubusercontent.com/12456965/64867676-26df5e00-d63e-11e9-814e-6b87cd13e1bc.gif)

**Comment by valllllll2000** [comment] 2019-09-25 13:47
Unfortunately there seems to be a bug with mapbox https://github.com/mapbox/mapbox-gl-native/issues/15631 
I have created a test app for them to reproduce the issue and hopefully it will be fixed but it may take some time.
In the meantime, what I will do is mitigate the issue. The text with latitude and longitude will not be visible when adding points offline but at least the points will be.

**Comment by valllllll2000** [comment] 2019-09-26 15:03
## Test plan
Test creating/ editing multiple geoshapes types: lines, points, areas. Also try creating a geoshape with manual input disabled.
Download an offline map and select it to use (you can get to offline maps from navigation drawer).
Set device in flight mode.
Try creating geoshapes, the selected area should be displayed.

**Comment by janagombitova** [comment] 2019-10-02 11:32
Works like a charm

**Closed** 2019-10-03 09:12 UTC
Labels: Ready for Release
