### ISSUE TITLE
Data point History shows no answers 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#873] opened 2017-09-18 10:07 UTC
While testing the UAT1 build of the 2.4.0.1 apk I noticed that after syncing in data points, the History of the point does show the submitted forms but not the answers anymore. All is empty.

**Comment by valllllll2000** [comment] 2017-10-02 15:12
@janagombitova I have just checked and everything shows correctly for me. I synced several forms to my device and all the answers for all the forms that were filled and showed in the history tab were displayed correctly on my nexus 6p with android 8.0. Could you please give me an example of survey/form and datapoint for which you reproduced it? Which device did you use?

**Comment by janagombitova** [comment] 2017-10-04 10:17
@valllllll2000 Strange indeed. I have tested now and the History for the forms I have on my phone and synced in also shows properly now. Not sure what happened with the last tests and I do not remember which exact surveys I tried out, to replicate my steps. 

So for now, lets consider this issue resolved and hope it will not show up.

**Comment by janagombitova** [comment] 2017-10-10 13:00
@valllllll2000 hey, so I have been testing on UAT1 _1.9.24 and 2.4.0.1 UAT tests > Montoring > 1.9.24 testing Nikki's cleaning and I have synced in the data for the 1st time to two devices and with one I had no issues with the History and with the 2nd I did. Here are the details: 

- mobile phone: 
- tablet: 

I checked data point "e" and here is what I saw in the History after opening the submitted form: 
- on the mobile phone: 
   - basic info group answers showed 
   - repeated group (one repetition) answers did not show 
   - another group answers showed 
- on the tablet: 
   - basic info group answers did not show 
   - repeated group (one repetition) answers showed 
   - another group answers did not show

I checked data point "a" and here is what I saw in the History after opening the submitted form: 
- on the mobile phone: 
   - basic info group answers showed 
   - repeated group (two repetitions) answers showed 
   - another group answers showed 
- on the tablet: 
   - basic info group answers did not show 
   - repeated group (two repetitions) answers showed 
   - another group answers did not show

I checked data point "b" and here is what I saw in the History after opening the submitted form: 
- on the mobile phone: 
   - basic info group answers showed 
   - repeated group (two repetitions) answers showed 
   - another group answers showed 
- on the tablet: 
   - basic info group answers did not show 
   - repeated group (two repetitions) answers showed 
   - another group answers did not show

I checked data point "c" and here is what I saw in the History after opening the submitted form: 
- on the mobile phone: 
   - basic info group answers showed 
   - repeated group (one repetition) answers did not show 
   - another group answers showed 
- on the tablet: 
   - basic info group answers did not show 
   - repeated group (one repetition) answers showed 
   - another group answers did not show

**Comment by valllllll2000** [comment] 2017-10-11 13:48
I checked data point "e" and here is what I saw in the History after opening the submitted form: 
- on the mobile phone: 
   - basic info group answers showed **Unable to reproduce**
   - repeated group (one repetition) answers did not show **Should be fixed**
   - another group answers showed 
- on the tablet: 
   - basic info group answers did not show  **Unable to reproduce**
   - repeated group (one repetition) answers showed **Should be fixed**
   - another group answers did not show  **Unable to reproduce**

**Comment by janagombitova** [comment] 2017-10-12 08:26
From testing on the newer devices all seems working fine. All History answers show, with images, signatures, shapes and in RQGs, etc. 👍  Let's hope there are no surprises lingering in the shadows

**Closed** 2017-10-13 10:15 UTC
Labels: Ready for release, Resolved issues
